name: trip_go
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  http: ^1.3.0
  shared_preferences: ^2.3.3
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^3.0.3
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/avatar_placeholder.png

